### ISSUE TITLE
Negative item effects from random loot or chests - submitted as pull request.

### ISSUE THREAD

**Issue by dwarf74** [CephalofairGames/frosthaven-faq#18]
The original reads as though the choice not to equip is dependent on not having the relevant perk, which is not the intended meaning. It also reads as though gaining the -1s are required if you equip the item, which is also not quite the intended meaning (since those -1s are avoided by having the perk!).

Instead, note that you can always choose not to equip an item. Adding the -1s is contingent on equipping the item sans relevant perk.

**Comment by gpoirier** [comment]
I'd recommend linking the PRs and the issues, by using a link in the description to the PR from the issue, and/or to the issue from the PR. In this case it looks like PR #16 

I'd also recommend always having changes go through a PR that makes it easier for others to review changes before they get included in the main branch, makes it easier for others to follow changes and to have a chance to catch potential mistakes

I'm making those suggestion since you'v'e mentioned on BGG that you're new to git/github
